### PR TITLE
Fix the tests I broke with previous changes

### PR DESCRIPTION
**Pull request by nick96**
Moving things to querying Athena, rather than logic in the plugin, meant that some of the tests are no longer necessary.

### CODE REVIEW

**Comment by ikramsaedi** [comment]
Drive by question as a non platform engineer:

What is Athena?

**Comment by nick96** [comment]
> Drive by question as a non platform engineer:
> 
> What is Athena?

It's an AWS service that lets you query data stored in S3 like it's a relational database: https://aws.amazon.com/athena/. In this context, we store trace data in S3 because it's super cheap (way cheaper than Elasticsearch which is where we previosuly stored it). Then we need a way of querying that data to show it in the tracing UI. Athena lets us do that in an easy/efficient way.

**Comment by ikramsaedi** [comment]
Thank you so much Nick! ❤️

**Review by eepmoi — APPROVED** [review]
LGTM!

**Pull request merged**
